server:
  port: 8503

spring:
  application:
    name: booking-consumer-service
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:ecabDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbit:
  data:
    queue:
      message:
        audit: "queue.message.audit"
      booking:
        add: "queue.booking.add"
        edit: "queue.booking.edit"
        delete: "queue.booking.delete"

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/